### ISSUE TITLE
Fails to open a popup in Safari

### ISSUE THREAD

**Issue by agektmr** [pwa-builder/pwa-auth#3] opened 2020-04-15 00:41 UTC
When I try to use this on https://pwa-auth-basic.glitch.me and click on one of auth button, it fails to open a popup window saying "An error occurred: {"error":"popup_blocked_by_browser"}".

**Comment by JudahGabriel** [comment] 2020-04-15 00:45
Ah, I see that on iOS Safari. Let me investigate, see what can be done. Thanks for the bug report.

**Comment by JudahGabriel** [comment] 2020-04-15 02:24
OK, the issue is that iOS Safari is a little too zealous on the popup blocking. In particular:

1. User clicks Sign in with X
2. Auth library is lazy loaded -- this causes a slight delay...
3. Auth library is loaded and, on first run, OAuth window is launched

iOS Safari is blocking #3, thinking it's an unwanted popup due to the delay between user interaction and window launch.

Let me think about how best to handle this without getting rid of lazy loading. I'll get back to you tomorrow.

**Comment by balupton** [comment] 2020-04-16 06:31
Demo works fine for me in ios safari. I get the prompt below and proceed as normal

![EDBDB156-B6F9-45EF-BB48-2BEEAE81560A](https://user-images.githubusercontent.com/61148/79422110-94ea6a00-7fff-11ea-8106-1643b225970a.png)

However, when I refresh the page, I am logged out again, for all the various demos - is this normal?

**Comment by balupton** [comment] 2020-04-16 06:45
On chrome on ios I get popup blocked error, along with a always show popup browser modal button, however, when i login once showing the popup, the popup just hangs on one moment please. However closing the tab and opening it again, remembers the popup prefence and everything logs in smoothly

**Comment by balupton** [comment] 2020-04-16 15:40
Same behaviour as above with chrome on safari for mac - popup blocked, so then I go to the navbar, enable the popup, signin in the popup, but it just stays on `One moment please…` and the app page says `An error occurred: {"error":"popup_blocked_by_browser"}` so seems like the library is giving up when the popup is blocked, rather than expecting the user to enable them in the same session.

<img width="1283" alt="Screen Shot 2020-04-17 at 1 38 20 am" src="https://user-images.githubusercontent.com/61148/79476489-63e45680-804c-11ea-99bf-d7f3b9072d89.png">

**Comment by balupton** [comment] 2020-04-16 15:45
Published a video of the above on safari on mac here:

https://youtu.be/pznF8XQ4USY

**Comment by JudahGabriel** [comment] 2020-04-16 20:27
Thanks for the heads up. iOS WebKit (which is used by Safari and Chrome on iOS) has a different model for detecting unwanted popups.

I have a fix in the works -- it will be released later today. Thanks for the videos and documenting the issue! I'll post here when the fix is available.

**Comment by JudahGabriel** [comment] 2020-04-18 18:52
Hi friends, I rolled out a fix for Safari. I tested on my iPhone and it works as expected. I'll test on desktop Safari soon, but I believe that is fixed as well.

Closing! Let me know if you see any additional issues.

**Closed by JudahGabriel** 2020-04-18 18:52 UTC

**Comment by francescogatto** [comment] 2021-11-17 16:06
How did you resolved that? wich commit?
